# Generated by Django 2.2 on 2022-02-28 11:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import ethracker.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-fA-F0-9]*$', 'Only hexadecimal characters are allowed.'), django.core.validators.MinLengthValidator(40)])),
                ('current_balance', models.DecimalField(blank=True, decimal_places=18, default=None, max_digits=19, null=True)),
                ('confirmed_balance', models.DecimalField(blank=True, decimal_places=18, default=None, max_digits=19, null=True)),
                ('confirmed_blocks_no', models.IntegerField(blank=True, default=None, null=True)),
                ('total_deduced', models.DecimalField(blank=True, decimal_places=18, default=None, max_digits=19, null=True)),
                ('total_deposit', models.DecimalField(blank=True, decimal_places=18, default=None, max_digits=19, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, ethracker.models.mixins.CoreModel),
        ),
    ]
