# Generated by Django 2.2 on 2022-02-28 16:18

from django.db import migrations, models
import django.utils.timezone
import ethracker.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40, unique=True)),
                ('current_balance', models.BigIntegerField(blank=True, default=None, null=True)),
                ('confirmed_balance', models.BigIntegerField(blank=True, default=None, null=True)),
                ('confirmed_blocks_no', models.IntegerField(blank=True, default=None, null=True)),
                ('total_deduced', models.BigIntegerField(default=0)),
                ('total_deposit', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=(models.Model, ethracker.models.mixins.CoreModel),
        ),
    ]
