version: "2.5"

services:
  # Deploy the broker.
  web_tests:
    build:
      context: .
      dockerfile: infrastructure/web.Dockerfile
    command: python manage.py test ethracker.tests --settings=tracker.settings.test
    volumes:
      - .:/tracker_tests
    ports:
      - "8000:8000"
