version: "2.5"

services:
  web_tests:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: python manage.py test ethracker.tests --settings=tracker.settings.test
    volumes:
      - .:/tracker
    ports:
      - "8000:8000"
