version: "2.5"

services:
  # Deploy the broker.
  rabbitmq_server:
    image: rabbitmq:3-management
    ports:
      # Expose the port for the worker to add/get tasks
      - 5672:5672
      # OPTIONAL: Expose the GUI port
      - 15672:15672

  # Deploy the worker
  worker:
    # Build using the worker Dockerfile
    build:
      context: .
      dockerfile: worker.Dockerfile
    network_mode: host
    environment:
      C_FORCE_ROOT: "yes"
      rabbitmq_uri: amqp://127.0.0.1:5672
    depends_on:
      - rabbitmq_server

  beat:
    # Build using the worker Dockerfile
    build:
      context: .
      dockerfile: beat.Dockerfile
    network_mode: host
    environment:
      rabbitmq_uri: amqp://127.0.0.1:5672
    depends_on:
      - rabbitmq_server
      - worker

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 --settings=tracker.settings.production
    volumes:
      - .:/tracker
    ports:
      - "8000:8000"
    depends_on:
      - beat
